### ISSUE TITLE
Create an overall model that includes all model blocks

### ISSUE THREAD

**Issue by valearna** [rishabgit/genomic-info-from-papers#10]
We need an overall model that combines NER, BOW and regex model blocks. We might also need to add a BOW model block, which is currently missing in case the BOW entity extractor is not sufficient as is. The overall model should have arguments to select different options for the individual blocks and to include/exclude them.

**Comment by rishabgit** [comment]
https://github.com/rishabgit/genomic-info-from-papers/commit/c3a24d197158f98a145813e2a5cee6e88b8f9f9c
